# -*- coding: utf-8 -*-
"""Data Prepricesing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14KiyXgqucHe8sTXBMZzHz2y0nBa0_2em
"""

import pandas as pd
import numpy as np

file1 = open("/content/door_open.txt","r")

st = file1.read()
st= st.split("\n")

df = pd.DataFrame()

a=[]
b=[]
c=[]
d=[]
e=[]
f=[]
time=[]
for x in st:
  y=x.split(": ")
  time.append(y[0])
  a1,b1,c1,d1,e1,f1,g=y[1].split(", ")
  
  a1=a1.split("[")[1]
  f1=f1.split("]")[0]
  a.append(float(a1.strip()))
  b.append(float(b1.strip()))
  c.append(float(c1.strip()))
  d.append(float(d1.strip()))
  e.append(float(e1.strip()))
  f.append(float(f1.strip()))



df["X"]=a

df["Y"]=b

df["A"]=c
df["B"]=d

df["C"]=e
df["D"]=f

df.head()

!pip install sklearn

from sklearn.impute import SimpleImputer



imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer= imputer.fit(df)

df=imputer.transform(df)

from sklearn.preprocessing import StandardScaler

st_x= StandardScaler()
x= st_x.fit_transform(df)

x1=x

x1[0:5]

from sklearn.cluster import AgglomerativeClustering

model = AgglomerativeClustering(n_clusters=3)
# fit model and predict clusters
yhat = model.fit_predict(df)

yhat

df = pd.DataFrame()

df["Timestamp"] = time
df["X"]=a

df["Y"]=b

df["A"]=c
df["B"]=d

df["C"]=e
df["D"]=f

df["door_status"]=yhat

df.head()

df.to_csv("Training_Data.csv")

